name = "ChebyshevFiltering"
uuid = "1d56a567-eebb-4d79-96f4-589d6165ccdd"
authors = ["Dario-Rosa85 <dario.rosa85@gmail.com>"]
version = "0.1.0"

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
